/**
 * MIT License
 *
 * @brief Tiny JSON loader for RcConfig using ArduinoJson.
 *
 * @file Json.hpp
 * @author Little Man Builds (Darren Osborne)
 * @date 2025-10-08
 * @copyright Copyright (c) 2026 Little Man Builds
 *
 */

#pragma once

#include "Config.hpp"
#include "Types.hpp"

#include <ArduinoJson.h>

#include <cstddef>
#include <string.h>
#include <utility>

namespace rc
{
// RC_DECLARE_ROLES include-order requirement:
//
// This header relies on helpers generated by RC_DECLARE_ROLES(Enum, ...):
//   - rc::to_string(Enum)  -> const char*
//   - rc::role_count(Enum) -> std::size_t
//
// Roles must be declared BEFORE including this file, e.g.:
//
//   #define MY_ROLES(_)...; RC_DECLARE_ROLES(MyEnum, MY_ROLES)
//   #include "Json.hpp"
//
// The guard below produces a compile error if that order is violated.

/// @brief Prove that role-name helpers were generated before this header was included.
template <typename E> inline void require_role_helpers()
{
    using ToStringFn = const char *(*)(E);
    // Check that an overload with signature `const char*(E)` exists:
    (void)sizeof((ToStringFn)&rc::to_string);
    // Check that role_count(E) is callable and forms a complete type:
    (void)sizeof(rc::role_count(std::declval<E>()));
}

/// @brief Look up enum value by role name via RC_DECLARE_ROLES helpers.
template <typename E> inline bool role_from_name(const char *name, E &out)
{
    require_role_helpers<E>();

    if (!name)
        return false;

    const std::size_t n = rc::role_count(E{});
    for (std::size_t i = 0; i < n; ++i)
    {
        const E e = static_cast<E>(i);
        const char *rn = rc::to_string(e);
        if (rn && ::strcmp(rn, name) == 0)
        {
            out = e;
            return true;
        }
    }
    return false;
}

/**
     * @brief Load RcConfig from a JSON string.
     * @code
     * // Schema:
     * {
     *   "map": { "RoleName": 0, ... },
     *   "axes": {
     *     "RoleName": {
     *       "raw": [lo, hi, center],
     *       "deadband_us": 0,
     *       "out": [lo, hi],
     *       "center_out": 0,
     *       "expo": 0.0,
     *       "invert": true
     *     }
     *   },
     *   "switches": {
     *     "RoleName": {
     *       "values": [0,1,2],
     *       "raw_levels": [1000,1500,2000],
     *       "auto_levels": true,
     *       "hyst_us": 60,
     *       "learn_alpha": 0.2,
     *       "min_sep_us": 120
     *     }
     *   }
     * }
     * @endcode
     */
template <typename E> bool load_json(E /*tag*/, RcConfig<E> &cfg, const char *json)
{
    require_role_helpers<E>();

    if (!json)
        return false;

    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, json);
    if (err)
        return false;

    // ---- Map ---- //

    if (doc["map"].is<JsonObject>())
    {
        JsonObject map = doc["map"].as<JsonObject>();
        for (JsonPair kvp : map)
        {
            const char *roleName = kvp.key().c_str();
            const int ch = kvp.value().as<int>();
            if (ch < 0 || ch >= static_cast<int>(kRcMaxReceiverChannels))
                return false;

            E role{};
            if (role_from_name(roleName, role))
                cfg.map(role, static_cast<std::uint8_t>(ch));
        }
    }

    // ---- Axes ---- //

    if (doc["axes"].is<JsonObject>())
    {
        JsonObject axes = doc["axes"].as<JsonObject>();
        for (JsonPair kvp : axes)
        {
            const char *roleName = kvp.key().c_str();
            E role{};
            if (!role_from_name(roleName, role))
                continue;

            auto b = cfg.axis(role);
            JsonObject a = kvp.value().as<JsonObject>();

            if (a["raw"].is<JsonArray>())
            {
                JsonArray ra = a["raw"].as<JsonArray>();
                if (ra.size() >= 2)
                {
                    const int lo = ra[0].as<int>();
                    const int hi = ra[1].as<int>();
                    const int ct = (ra.size() >= 3) ? ra[2].as<int>() : ((lo + hi) / 2);
                    const int i16_lo = detail::kInt16MinValue;
                    const int i16_hi = detail::kInt16MaxValue;
                    if (lo < i16_lo || lo > i16_hi || hi < i16_lo || hi > i16_hi || ct < i16_lo || ct > i16_hi)
                        return false;
                    b.raw(static_cast<std::int16_t>(lo), static_cast<std::int16_t>(hi), static_cast<std::int16_t>(ct));
                }
            }

            if (a["deadband_us"].is<int>())
            {
                const int db = a["deadband_us"].as<int>();
                if (db < detail::kInt16MinValue || db > detail::kInt16MaxValue)
                    return false;
                b.deadband_us(static_cast<std::int16_t>(db));
            }

            if (a["out"].is<JsonArray>())
            {
                JsonArray out = a["out"].as<JsonArray>();
                if (out.size() >= 2)
                    b.out(out[0].as<float>(), out[1].as<float>());
            }

            if (a["center_out"].is<float>() || a["center_out"].is<int>())
                b.center_out(a["center_out"].as<float>());

            if (a["expo"].is<float>() || a["expo"].is<int>())
                b.expo(a["expo"].as<float>());

            if (a["invert"].is<bool>())
                b.invert(a["invert"].as<bool>());

            (void)b.done();
        }
    }

    // ---- Switches ---- //

    if (doc["switches"].is<JsonObject>())
    {
        JsonObject sws = doc["switches"].as<JsonObject>();
        for (JsonPair kvp : sws)
        {
            const char *roleName = kvp.key().c_str();
            E role{};
            if (!role_from_name(roleName, role))
                continue;

            JsonObject s = kvp.value().as<JsonObject>();
            auto b = cfg.sw(role);

            if (s["values"].is<JsonArray>())
            {
                JsonArray values = s["values"].as<JsonArray>();
                if (values.size() > kRcMaxSwitchVals)
                    return false;
                float v[kRcMaxSwitchVals]{};
                std::uint8_t n = 0;
                for (JsonVariant it : values)
                {
                    v[n++] = it.as<float>();
                }
                switch (n)
                {
                default:
                case 0:
                    b.values({});
                    break;
                case 1:
                    b.values({v[0]});
                    break;
                case 2:
                    b.values({v[0], v[1]});
                    break;
                case 3:
                    b.values({v[0], v[1], v[2]});
                    break;
                case 4:
                    b.values({v[0], v[1], v[2], v[3]});
                    break;
                case 5:
                    b.values({v[0], v[1], v[2], v[3], v[4]});
                    break;
                case 6:
                    b.values({v[0], v[1], v[2], v[3], v[4], v[5]});
                    break;
                case 7:
                    b.values({v[0], v[1], v[2], v[3], v[4], v[5], v[6]});
                    break;
                case 8:
                    b.values({v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7]});
                    break;
                }
            }

            if (s["raw_levels"].is<JsonArray>())
            {
                JsonArray raw_levels = s["raw_levels"].as<JsonArray>();
                if (raw_levels.size() > kRcMaxSwitchVals)
                    return false;
                std::int16_t lv[kRcMaxSwitchVals]{};
                std::uint8_t n = 0;
                for (JsonVariant it : raw_levels)
                {
                    const int raw = it.as<int>();
                    if (raw < detail::kInt16MinValue || raw > detail::kInt16MaxValue)
                        return false;
                    lv[n++] = static_cast<std::int16_t>(raw);
                }
                switch (n)
                {
                default:
                case 0:
                    break;
                case 1:
                    b.raw_levels({lv[0]});
                    break;
                case 2:
                    b.raw_levels({lv[0], lv[1]});
                    break;
                case 3:
                    b.raw_levels({lv[0], lv[1], lv[2]});
                    break;
                case 4:
                    b.raw_levels({lv[0], lv[1], lv[2], lv[3]});
                    break;
                case 5:
                    b.raw_levels({lv[0], lv[1], lv[2], lv[3], lv[4]});
                    break;
                case 6:
                    b.raw_levels({lv[0], lv[1], lv[2], lv[3], lv[4], lv[5]});
                    break;
                case 7:
                    b.raw_levels({lv[0], lv[1], lv[2], lv[3], lv[4], lv[5], lv[6]});
                    break;
                case 8:
                    b.raw_levels({lv[0], lv[1], lv[2], lv[3], lv[4], lv[5], lv[6], lv[7]});
                    break;
                }
            }

            if (s["auto_levels"].is<bool>())
                b.auto_levels(s["auto_levels"].as<bool>());

            if (s["hyst_us"].is<int>())
            {
                const int hyst = s["hyst_us"].as<int>();
                if (hyst < 0 || hyst > 65535)
                    return false;
                b.hysteresis_us(static_cast<std::uint16_t>(hyst));
            }

            if (s["learn_alpha"].is<float>() || s["learn_alpha"].is<int>())
                b.learn_alpha(s["learn_alpha"].as<float>());

            if (s["min_sep_us"].is<int>())
            {
                const int min_sep = s["min_sep_us"].as<int>();
                if (min_sep < 0 || min_sep > 65535)
                    return false;
                b.min_sep_us(static_cast<std::uint16_t>(min_sep));
            }

            (void)b.done();
        }
    }

    return true;
}

} // namespace rc
#ifndef RCLINK_NO_LEGACY_GLOBAL_ALIASES
using rc::load_json;
#endif
